### ISSUE TITLE
{"path"=>"The root path (\"/\") is not allowed."}

### ISSUE THREAD

**Issue by denmarkmeralpis** [robin850/carrierwave-dropbox#10]
What happen?

**Comment by indywebco** [comment]
I am having this issue currently, just arose within last 48 hours. The uploader worked fine for the last two months, but just broke a few days ago. Here is the error:

DropboxError ({"path"=>"The root path (\"/\") is not allowed."}):

Anything to do with recent Dropbox API endpoint updates?  Any help would be appreciated.

**Comment by indywebco** [comment]
Also - on my local environment, using the exact same Dropbox API keys (generated from the rake task) that are authenticated on live server, I get a User Not Authenticated error. It's really odd, any help would be appreciated.
