### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by famousky** [robin850/carrierwave-dropbox#17]
I followed tutorial here on Git and I am getting this error now. I have file in config/initializers/carrierwave.rb with filled dropbox API info:

```
CarrierWave.configure do |config|
  config.dropbox_app_key = ENV["APP_KEY"]
  config.dropbox_app_secret = ENV["APP_SECRET"]
  config.dropbox_access_token = ENV["ACCESS_TOKEN"]
  config.dropbox_access_token_secret = ENV["ACCESS_TOKEN_SECRET"]
  config.dropbox_user_id = ENV["USER_ID"]
  config.dropbox_access_type = "dropbox"
end
```

and I enabled **storage :dropbox** in my uploaders.

This error triggers on this line of code in my views (when I remove this line everything works fine):
```
= link_to image_tag(current_user.avatar.icon), root_url, :class => "circle icon"
```

OR when I remove this line and try to upload an image to Dropbox, here:

![screen shot 2015-04-08 at 8 57 28 pm](https://cloud.githubusercontent.com/assets/4720153/7045576/f81b9272-de31-11e4-9ca2-fa0b3f3d5639.png)

Is this issue with my setup or something else?

**Comment by famousky** [comment]
Fixed it. I was passing wrong values in carrierwave-dropbox configuration.

**Comment by PaulBrunache** [comment]
what was the wrong value?
