### ISSUE TITLE
v1_retired

### ISSUE THREAD

**Issue by bluespheal** [robin850/carrierwave-dropbox#29]
Dropbox just ditched API v1 and I'm getting the error "v1_retired", I'm pretty new to this stuff and I couldn't find an answer onto how to make the gem work, is there a configuration I need to change in order to get API v2 to work or does the gem need to be updated?

**Comment by vicvans20** [comment]
@bluespheal The gem needs to be updated but if you look at the commits you can see that it was last updated years ago, so sadly it probably won't get updated.

**Comment by bluespheal** [comment]
thanks for the response, I saw a pull request adding API2 but was never really implemented, hopefully this gem is updated since right now it's not usable anymore, and I've found it's really useful.

**Comment by zia-qamar** [comment]
Is there any other alternative for this gem?

**Comment by miccheng** [comment]
@robin850 Any thoughts?

**Comment by robin850** [comment]
Hi there,

Sorry for the late answer, I didn't find much time to work on open source recently but I hope to update this gem as soon as possible ; I will post a comment there when things get fixed.

**Comment by muatsoftgit** [comment]
I have the same errors in my project where I use this **gem**.

**Comment by xndryk** [comment]
the same.

**Comment by robin850** [comment]
Hey there !

Sorry for the very late answer. Version 2.0.0.rc1 has been pushed to RubyGems with the support for Dropbox API version 2. Feel free to create a new ticket to report any problem before the final release (in ~two weeks or so). You can have a look at #31 for further information. Thanks for your patience ! ❤️
