### ISSUE TITLE
Gem doesn't work with the new Dropbox v2 api

### ISSUE THREAD

**Issue by patrickoramah** [robin850/carrierwave-dropbox#33]
I'm currently using this gem in my app and lately it started crashing during file upload to Dropbox, when'll this gem be updated to support the new Dropbox v2 api?

**Comment by robin850** [comment]
Hello @patrickoramah,

Actually 2.0.0.rc1 was released a few months ago but I was waiting for eventual problems before the final release but I forgot to push it to RubyGems. Version 2.0.0 is now available and should be compatible with the Dropbox version 2 API. Thanks for reporting !
