### ISSUE TITLE
rake dropbox:authorize is not working

### ISSUE THREAD

**Issue by shamithc** [robin850/carrierwave-dropbox#4]
In Rails,

Rake Task:- rake dropbox:authorize APP_KEY=app_key APP_SECRET=app_secret ACCESS_TYPE=dropbox|app_folder is breaking 

Got following error,

rake aborted!
Don't know how to build task 'dropbox:authorize'

(See full trace by running task with --trace)

**Comment by Masroor71** [comment]
hello there!I'm a newbie and stuck with the similar problem 

rake aborted!
Don't know how to build task 'dropbox:authorize'


Could anyone please help me!
