### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by tochman** [robin850/carrierwave-dropbox#7]
Hi,

I'm getting `undefined method 'gsub' for nil:NilClass` when trying to upload file to dropbox.

My `/config/initializers/carrierwave.rb`looks like this:

``` ruby
CarrierWave.configure do |config|
  config.root = Rails.root.join('tmp')
  config.dropbox_app_key = ENV["..."]
  config.dropbox_app_secret = ENV["..."]
  config.dropbox_access_token = ENV["..."]
  config.dropbox_access_token_secret = ENV["..."]
  config.dropbox_user_id = ENV["..."]
  config.dropbox_access_type = "dropbox"
end
```

In `uploaders/avataruploader.rb` i have: 

```
storage :dropbox
```

![skarmavbild 2013-12-23 kl 14 10 05](https://f.cloud.github.com/assets/5248170/1800806/9d8a6fa8-6bd3-11e3-9343-ae1704a4939a.png)

What have I missed?

**Comment by userna21** [comment]
im have same problem, but i dont understand what is ENV? anyone help me?

**Comment by simplytrish** [comment]
Hello, I have my environment variables set up, but I still get this error.
